export enum ConfidenceLevel {
  UNSELECTED = "Unselected",
  FAIR_ATTEMPT = "FAIR ATTEMPT",
  OPTIMISTIC = "OPTIMISTIC",
  FAIRLY_CONFIDENT = "FAIRLY CONFIDENT",
  CONFIDENT = "CONFIDENT",
  HIGHLY_CONFIDENT = "HIGHLY CONFIDENT",
}

export enum ApplicationStage {
  SAVED = "SAVED",
  PREPARING = "PREPARING",
  APPLIED = "APPLIED",
  INTERVIEWING = "INTERVIEWING",
  REJECTED = "REJECTED",
  ARCHIVED = "ARCHIVED",
  NEGOTIATING = "NEGOTIATING",
  OFFER_ACCEPTED = "ACCEPTED OFFER",
  OFFER_REJECTED = "REJECTED OFFER",
}
